// Sake_redesign/src/app/pages/stats.tsx
import React, { useState, useMemo } from 'react';
import {
  BookOpen,
  Flame,
  Clock,
  TrendingUp,
  Calendar,
  BarChart3,
  Zap,
  Trophy,
  ChevronLeft,
  ChevronRight,
} from 'lucide-react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  AreaChart,
  Area,
  PieChart,
  Pie,
  Cell,
  LineChart,
  Line,
} from 'recharts';
import { statsData, type DailyReading } from '../lib/stats-data';
import { mockBooks } from '../lib/mock-data';

// ─── Color Palette ──────────────────────────────────────────────
const GOLD = '#c9a962';
const GOLD_DIM = '#5a4a2a';
const GREEN = '#4ade80';
const BLUE = '#60a5fa';
const PURPLE = '#c084fc';
const RED = '#f87171';
const MUTED = '#3a3d4a';
const CARD_BG = '#1a1d27';
const GRID_COLOR = 'rgba(255,255,255,0.04)';

// ─── Heatmap color scale ────────────────────────────────────────
function getHeatColor(pages: number, maxPages: number): string {
  if (pages === 0) return '#1e2230';
  const ratio = pages / maxPages;
  if (ratio < 0.15) return '#2a2518';
  if (ratio < 0.3) return '#3d3520';
  if (ratio < 0.5) return '#5a4a2a';
  if (ratio < 0.7) return '#8a7540';
  return '#c9a962';
}

const DAYS = ['Mon', '', 'Wed', '', 'Fri', '', 'Sun'];
const MONTHS_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

// ─── Custom Tooltip ─────────────────────────────────────────────
function CustomTooltip({ active, payload, label }: any) {
  if (!active || !payload || !payload.length) return null;
  return (
    <div className="bg-[#1a1d27] border border-border rounded-lg px-3 py-2 shadow-xl">
      <p className="text-xs text-muted-foreground mb-1">{label}</p>
      {payload.map((entry: any, i: number) => (
        <p key={i} className="text-sm" style={{ color: entry.color || GOLD }}>
          {entry.name}: {typeof entry.value === 'number' ? entry.value.toLocaleString() : entry.value}
        </p>
      ))}
    </div>
  );
}

// ─── Contribution Heatmap Component ─────────────────────────────
function ReadingHeatmap({ data }: { data: DailyReading[] }) {
  const [tooltipData, setTooltipData] = useState<{ date: string; pages: number; x: number; y: number } | null>(null);

  const { weeks, maxPages, monthLabels } = useMemo(() => {
    // Get last 52 weeks of data
    const endDate = new Date('2026-02-28');
    const startDate = new Date(endDate);
    startDate.setDate(startDate.getDate() - 363); // ~52 weeks

    // Adjust start to Monday
    while (startDate.getDay() !== 1) {
      startDate.setDate(startDate.getDate() - 1);
    }

    const dateMap = new Map(data.map((d) => [d.date, d.pagesRead]));
    const weeksArr: { date: string; pages: number; dayOfWeek: number }[][] = [];
    let currentWeek: { date: string; pages: number; dayOfWeek: number }[] = [];
    let maxP = 0;
    const monthLabelPositions: { label: string; col: number }[] = [];
    let lastMonth = -1;

    const cursor = new Date(startDate);
    let weekIdx = 0;

    while (cursor <= endDate) {
      const dateStr = cursor.toISOString().split('T')[0];
      const dayOfWeek = cursor.getDay();
      // Convert Sun=0..Sat=6 to Mon=0..Sun=6
      const adjustedDay = dayOfWeek === 0 ? 6 : dayOfWeek - 1;
      const pages = dateMap.get(dateStr) || 0;
      if (pages > maxP) maxP = pages;

      currentWeek.push({ date: dateStr, pages, dayOfWeek: adjustedDay });

      // Track month labels
      const m = cursor.getMonth();
      if (m !== lastMonth) {
        monthLabelPositions.push({ label: MONTHS_SHORT[m], col: weekIdx });
        lastMonth = m;
      }

      if (adjustedDay === 6) {
        weeksArr.push(currentWeek);
        currentWeek = [];
        weekIdx++;
      }

      cursor.setDate(cursor.getDate() + 1);
    }

    if (currentWeek.length > 0) {
      weeksArr.push(currentWeek);
    }

    return { weeks: weeksArr, maxPages: maxP, monthLabels: monthLabelPositions };
  }, [data]);

  const cellSize = 13;
  const cellGap = 3;
  const labelWidth = 28;
  const topPadding = 20;

  return (
    <div className="relative">
      {/* Month labels */}
      <div className="flex ml-[28px]" style={{ gap: 0 }}>
        {monthLabels.map((m, i) => (
          <span
            key={`${m.label}-${i}`}
            className="text-[10px] text-muted-foreground absolute"
            style={{ left: labelWidth + m.col * (cellSize + cellGap), top: 0 }}
          >
            {m.label}
          </span>
        ))}
      </div>

      <div className="flex items-start mt-1" style={{ paddingTop: topPadding }}>
        {/* Day labels */}
        <div className="shrink-0" style={{ width: labelWidth }}>
          {DAYS.map((day, i) => (
            <div
              key={i}
              className="text-[10px] text-muted-foreground"
              style={{ height: cellSize + cellGap, lineHeight: `${cellSize + cellGap}px` }}
            >
              {day}
            </div>
          ))}
        </div>

        {/* Grid */}
        <div className="flex overflow-x-auto" style={{ gap: cellGap }}>
          {weeks.map((week, wi) => (
            <div key={wi} className="flex flex-col" style={{ gap: cellGap }}>
              {Array.from({ length: 7 }, (_, di) => {
                const cell = week.find((c) => c.dayOfWeek === di);
                if (!cell) {
                  return (
                    <div
                      key={di}
                      style={{ width: cellSize, height: cellSize }}
                    />
                  );
                }
                return (
                  <div
                    key={di}
                    className="rounded-[3px] cursor-pointer transition-all hover:ring-1 hover:ring-white/20"
                    style={{
                      width: cellSize,
                      height: cellSize,
                      backgroundColor: getHeatColor(cell.pages, maxPages),
                    }}
                    onMouseEnter={(e) => {
                      const rect = e.currentTarget.getBoundingClientRect();
                      setTooltipData({
                        date: cell.date,
                        pages: cell.pages,
                        x: rect.left + rect.width / 2,
                        y: rect.top,
                      });
                    }}
                    onMouseLeave={() => setTooltipData(null)}
                  />
                );
              })}
            </div>
          ))}
        </div>
      </div>

      {/* Legend */}
      <div className="flex items-center justify-end gap-1.5 mt-3 text-[10px] text-muted-foreground">
        <span>Less</span>
        {[0, 0.15, 0.3, 0.5, 0.7, 1].map((ratio, i) => (
          <div
            key={i}
            className="rounded-[2px]"
            style={{
              width: 11,
              height: 11,
              backgroundColor: ratio === 0 ? '#1e2230' : getHeatColor(maxPages * ratio, maxPages),
            }}
          />
        ))}
        <span>More</span>
      </div>

      {/* Floating tooltip */}
      {tooltipData && (
        <div
          className="fixed z-50 bg-[#1a1d27] border border-border rounded-lg px-3 py-2 shadow-xl pointer-events-none"
          style={{
            left: tooltipData.x,
            top: tooltipData.y - 50,
            transform: 'translateX(-50%)',
          }}
        >
          <p className="text-xs text-muted-foreground">
            {new Date(tooltipData.date).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })}
          </p>
          <p className="text-sm text-foreground">
            {tooltipData.pages > 0
              ? `${tooltipData.pages} pages`
              : 'No reading'}
          </p>
        </div>
      )}
    </div>
  );
}

// ─── Stats Page ─────────────────────────────────────────────────
export function StatsPage() {
  const { daily, hourly, weekly, monthly, streak, totals } = statsData;
  const [dailyRange, setDailyRange] = useState<'7' | '14' | '30'>('30');

  // ─── Derived data ──────────────────────────
  const recentDaily = useMemo(() => {
    const days = parseInt(dailyRange);
    return daily.slice(-days).map((d) => ({
      ...d,
      label: new Date(d.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    }));
  }, [daily, dailyRange]);

  const booksByFormat = useMemo(() => {
    const counts: Record<string, number> = {};
    mockBooks.forEach((b) => {
      counts[b.format] = (counts[b.format] || 0) + 1;
    });
    return Object.entries(counts).map(([name, value]) => ({ name, value }));
  }, []);

  const booksByStatus = useMemo(() => {
    const counts: Record<string, number> = {};
    mockBooks.forEach((b) => {
      counts[b.status] = (counts[b.status] || 0) + 1;
    });
    return Object.entries(counts).map(([name, value]) => ({ name: name.charAt(0).toUpperCase() + name.slice(1), value }));
  }, []);

  const ratingDist = useMemo(() => {
    const counts = [0, 0, 0, 0, 0, 0]; // 0–5 stars
    mockBooks.forEach((b) => {
      counts[b.rating]++;
    });
    return counts.slice(1).map((count, i) => ({
      rating: `${i + 1}★`,
      count,
    }));
  }, []);

  const recentWeekly = weekly.slice(-12);

  const totalHours = Math.round(totals.totalMinutes / 60);
  const readingPercentage = Math.round((totals.daysActive / totals.totalDays) * 100);

  const FORMAT_COLORS = [BLUE, PURPLE, GOLD, GREEN, RED];
  const STATUS_COLORS = [MUTED, GOLD, GREEN];

  return (
    <div className="p-4 lg:p-6 space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          {
            icon: BookOpen,
            label: 'Total Pages Read',
            value: totals.totalPages.toLocaleString(),
            sub: `${totals.avgPagesPerDay} avg/day`,
            color: 'text-foreground',
            iconColor: GOLD,
          },
          {
            icon: Clock,
            label: 'Reading Time',
            value: `${totalHours}h`,
            sub: `${Math.round(totalHours / Math.max(1, totals.daysActive) * 60)}min avg/session`,
            color: 'text-[#60a5fa]',
            iconColor: BLUE,
          },
          {
            icon: Flame,
            label: 'Current Streak',
            value: `${streak.current} days`,
            sub: `Longest: ${streak.longest} days`,
            color: 'text-[#f87171]',
            iconColor: RED,
          },
          {
            icon: TrendingUp,
            label: 'Days Active',
            value: `${totals.daysActive}`,
            sub: `${readingPercentage}% of days`,
            color: 'text-[#4ade80]',
            iconColor: GREEN,
          },
        ].map((card) => (
          <div
            key={card.label}
            className="bg-card border border-border rounded-xl p-4"
          >
            <div className="flex items-center gap-2 mb-2">
              <div
                className="w-7 h-7 rounded-lg flex items-center justify-center"
                style={{ backgroundColor: card.iconColor + '15' }}
              >
                <card.icon className="w-3.5 h-3.5" style={{ color: card.iconColor }} />
              </div>
              <p className="text-xs text-muted-foreground">{card.label}</p>
            </div>
            <p className={`text-2xl ${card.color}`}>{card.value}</p>
            <p className="text-xs text-muted-foreground mt-0.5">{card.sub}</p>
          </div>
        ))}
      </div>

      {/* Highlight cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div className="bg-card border border-border rounded-xl p-4 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-[#c9a962]/10 flex items-center justify-center">
            <Trophy className="w-5 h-5 text-[#c9a962]" />
          </div>
          <div>
            <p className="text-xs text-muted-foreground">Best Reading Day</p>
            <p className="text-sm text-foreground">{totals.bestDay.pagesRead} pages</p>
            <p className="text-xs text-muted-foreground">
              {new Date(totals.bestDay.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>
          </div>
        </div>
        <div className="bg-card border border-border rounded-xl p-4 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-[#4ade80]/10 flex items-center justify-center">
            <Zap className="w-5 h-5 text-[#4ade80]" />
          </div>
          <div>
            <p className="text-xs text-muted-foreground">Avg on Active Days</p>
            <p className="text-sm text-foreground">{totals.avgPagesOnActiveDay} pages</p>
            <p className="text-xs text-muted-foreground">{totals.totalSessions} total sessions</p>
          </div>
        </div>
        <div className="bg-card border border-border rounded-xl p-4 flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-[#c084fc]/10 flex items-center justify-center">
            <BarChart3 className="w-5 h-5 text-[#c084fc]" />
          </div>
          <div>
            <p className="text-xs text-muted-foreground">Books in Library</p>
            <p className="text-sm text-foreground">{mockBooks.length} books</p>
            <p className="text-xs text-muted-foreground">
              {mockBooks.filter((b) => b.status === 'read').length} completed
            </p>
          </div>
        </div>
      </div>

      {/* Contribution Heatmap */}
      <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Calendar className="w-4 h-4 text-primary" />
            <h3>Reading Activity</h3>
          </div>
          <p className="text-xs text-muted-foreground">
            {totals.totalPages.toLocaleString()} pages in the last year
          </p>
        </div>
        <div className="overflow-x-auto">
          <ReadingHeatmap data={daily} />
        </div>
      </div>

      {/* Daily Pages Chart */}
      <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-primary" />
            Pages Per Day
          </h3>
          <div className="flex items-center bg-secondary rounded-lg p-0.5">
            {(['7', '14', '30'] as const).map((r) => (
              <button
                key={r}
                onClick={() => setDailyRange(r)}
                className={`px-2.5 py-1 rounded-md text-xs transition-all cursor-pointer ${
                  dailyRange === r
                    ? 'bg-card text-foreground shadow-sm'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                {r}d
              </button>
            ))}
          </div>
        </div>
        <div className="h-56">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={recentDaily} barSize={dailyRange === '7' ? 28 : dailyRange === '14' ? 18 : 8}>
              <CartesianGrid strokeDasharray="3 3" stroke={GRID_COLOR} vertical={false} />
              <XAxis
                dataKey="label"
                tick={{ fill: '#6b7280', fontSize: 10 }}
                tickLine={false}
                axisLine={{ stroke: GRID_COLOR }}
                interval={dailyRange === '30' ? 4 : dailyRange === '14' ? 1 : 0}
              />
              <YAxis
                tick={{ fill: '#6b7280', fontSize: 10 }}
                tickLine={false}
                axisLine={false}
                width={35}
              />
              <Tooltip content={<CustomTooltip />} cursor={{ fill: 'rgba(255,255,255,0.03)' }} />
              <Bar dataKey="pagesRead" name="Pages" fill={GOLD} radius={[3, 3, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Weekly Trend */}
        <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
          <h3 className="flex items-center gap-2 mb-4">
            <TrendingUp className="w-4 h-4 text-primary" />
            Weekly Trend
          </h3>
          <div className="h-52">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={recentWeekly}>
                <defs>
                  <linearGradient id="goldGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor={GOLD} stopOpacity={0.3} />
                    <stop offset="100%" stopColor={GOLD} stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke={GRID_COLOR} vertical={false} />
                <XAxis
                  dataKey="week"
                  tick={{ fill: '#6b7280', fontSize: 10 }}
                  tickLine={false}
                  axisLine={{ stroke: GRID_COLOR }}
                />
                <YAxis
                  tick={{ fill: '#6b7280', fontSize: 10 }}
                  tickLine={false}
                  axisLine={false}
                  width={35}
                />
                <Tooltip content={<CustomTooltip />} />
                <Area
                  type="monotone"
                  dataKey="pages"
                  name="Pages"
                  stroke={GOLD}
                  fill="url(#goldGradient)"
                  strokeWidth={2}
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Reading by Hour */}
        <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
          <h3 className="flex items-center gap-2 mb-4">
            <Clock className="w-4 h-4 text-primary" />
            Reading by Time of Day
          </h3>
          <div className="h-52">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={hourly} barSize={14}>
                <CartesianGrid strokeDasharray="3 3" stroke={GRID_COLOR} vertical={false} />
                <XAxis
                  dataKey="label"
                  tick={{ fill: '#6b7280', fontSize: 9 }}
                  tickLine={false}
                  axisLine={{ stroke: GRID_COLOR }}
                  interval={2}
                />
                <YAxis
                  tick={{ fill: '#6b7280', fontSize: 10 }}
                  tickLine={false}
                  axisLine={false}
                  width={35}
                />
                <Tooltip content={<CustomTooltip />} />
                <Bar dataKey="pages" name="Pages" fill={BLUE} radius={[3, 3, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Monthly Pages */}
        <div className="bg-card border border-border rounded-xl p-4 lg:p-6 lg:col-span-2">
          <h3 className="flex items-center gap-2 mb-4">
            <Calendar className="w-4 h-4 text-primary" />
            Monthly Overview
          </h3>
          <div className="h-56">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={monthly} barSize={20}>
                <CartesianGrid strokeDasharray="3 3" stroke={GRID_COLOR} vertical={false} />
                <XAxis
                  dataKey="month"
                  tick={{ fill: '#6b7280', fontSize: 10 }}
                  tickLine={false}
                  axisLine={{ stroke: GRID_COLOR }}
                />
                <YAxis
                  tick={{ fill: '#6b7280', fontSize: 10 }}
                  tickLine={false}
                  axisLine={false}
                  width={40}
                />
                <Tooltip content={<CustomTooltip />} />
                <Bar dataKey="pages" name="Pages" fill={GOLD} radius={[3, 3, 0, 0]} />
                <Bar dataKey="booksFinished" name="Books Finished" fill={GREEN} radius={[3, 3, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
          {/* Monthly table */}
          <div className="mt-4 overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="text-muted-foreground border-b border-border">
                  <th className="text-left py-2 pr-4">Month</th>
                  <th className="text-right py-2 px-3">Pages</th>
                  <th className="text-right py-2 px-3">Avg/Day</th>
                  <th className="text-right py-2 pl-3">Books Done</th>
                </tr>
              </thead>
              <tbody>
                {monthly.slice(-6).reverse().map((m) => (
                  <tr key={m.month} className="border-b border-border/30">
                    <td className="py-2 pr-4 text-foreground">{m.month}</td>
                    <td className="py-2 px-3 text-right text-secondary-foreground">{m.pages.toLocaleString()}</td>
                    <td className="py-2 px-3 text-right text-secondary-foreground">{m.avgPagesPerDay}</td>
                    <td className="py-2 pl-3 text-right">
                      {m.booksFinished > 0 ? (
                        <span className="text-[#4ade80]">{m.booksFinished}</span>
                      ) : (
                        <span className="text-muted-foreground">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Distribution Charts */}
        <div className="space-y-6">
          {/* Format Distribution */}
          <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
            <h3 className="text-sm mb-3">Books by Format</h3>
            <div className="h-40">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={booksByFormat}
                    cx="50%"
                    cy="50%"
                    innerRadius={35}
                    outerRadius={60}
                    paddingAngle={4}
                    dataKey="value"
                    stroke="none"
                  >
                    {booksByFormat.map((_, i) => (
                      <Cell key={i} fill={FORMAT_COLORS[i % FORMAT_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip content={<CustomTooltip />} />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="flex flex-wrap justify-center gap-3 mt-2">
              {booksByFormat.map((entry, i) => (
                <div key={entry.name} className="flex items-center gap-1.5">
                  <div
                    className="w-2.5 h-2.5 rounded-sm"
                    style={{ backgroundColor: FORMAT_COLORS[i % FORMAT_COLORS.length] }}
                  />
                  <span className="text-xs text-muted-foreground">
                    {entry.name} ({entry.value})
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Rating Distribution */}
          <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
            <h3 className="text-sm mb-3">Rating Distribution</h3>
            <div className="h-32">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={ratingDist} barSize={24}>
                  <XAxis
                    dataKey="rating"
                    tick={{ fill: '#6b7280', fontSize: 11 }}
                    tickLine={false}
                    axisLine={false}
                  />
                  <YAxis hide />
                  <Tooltip content={<CustomTooltip />} />
                  <Bar dataKey="count" name="Books" fill={GOLD} radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Status Distribution */}
          <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
            <h3 className="text-sm mb-3">Books by Status</h3>
            <div className="space-y-2">
              {booksByStatus.map((entry, i) => {
                const total = mockBooks.length;
                const pct = Math.round((entry.value / total) * 100);
                return (
                  <div key={entry.name}>
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-xs text-muted-foreground">{entry.name}</span>
                      <span className="text-xs text-foreground">{entry.value} ({pct}%)</span>
                    </div>
                    <div className="h-1.5 bg-[#1e2230] rounded-full overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-500"
                        style={{
                          width: `${pct}%`,
                          backgroundColor: STATUS_COLORS[i % STATUS_COLORS.length],
                        }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      {/* Streak Details */}
      <div className="bg-card border border-border rounded-xl p-4 lg:p-6">
        <h3 className="flex items-center gap-2 mb-4">
          <Flame className="w-4 h-4 text-[#f87171]" />
          Reading Streaks
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-xs text-muted-foreground mb-1">Current Streak</p>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl text-foreground">{streak.current}</span>
              <span className="text-sm text-muted-foreground">days</span>
            </div>
            <div className="flex items-center gap-1 mt-2">
              {Array.from({ length: Math.min(streak.current, 14) }, (_, i) => (
                <div
                  key={i}
                  className="w-3 h-3 rounded-sm"
                  style={{
                    backgroundColor: `rgba(248,113,113,${0.3 + (i / Math.min(streak.current, 14)) * 0.7})`,
                  }}
                />
              ))}
              {streak.current > 14 && (
                <span className="text-xs text-muted-foreground ml-1">+{streak.current - 14}</span>
              )}
            </div>
          </div>
          <div className="bg-secondary/30 rounded-xl p-4">
            <p className="text-xs text-muted-foreground mb-1">Longest Streak</p>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl text-foreground">{streak.longest}</span>
              <span className="text-sm text-muted-foreground">days</span>
            </div>
            <p className="text-xs text-muted-foreground mt-2">
              {new Date(streak.longestStart).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
              {' — '}
              {new Date(streak.longestEnd).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// z-ui/src/routes/stats/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Loading from '$lib/components/Loading.svelte';
	import { ZUI } from '$lib/client/zui';
	import type { ApiError } from '$lib/types/ApiError';
	import type { LibraryBook } from '$lib/types/Library/Book';
	import type {
		ReadingActivityDay,
		ReadingActivityStats
	} from '$lib/types/Stats/ReadingActivityStats';

	type DailyRange = 7 | 14 | 30;
	type BookStatus = 'Unread' | 'Reading' | 'Completed';

	const DAILY_RANGES: DailyRange[] = [7, 14, 30];
	const FORMAT_COLORS = ['#60a5fa', '#c084fc', '#c9a962', '#4ade80', '#f87171'];
	const STATUS_COLORS: Record<BookStatus, string> = {
		Unread: '#3a3d4a',
		Reading: '#c9a962',
		Completed: '#4ade80'
	};

	let isLoading = $state(true);
	let error = $state<ApiError | null>(null);
	let books = $state<LibraryBook[]>([]);
	let activity = $state<ReadingActivityStats | null>(null);
	let dailyRange = $state<DailyRange>(30);

	onMount(() => {
		void loadStats();
	});

	async function loadStats(): Promise<void> {
		isLoading = true;
		error = null;

		const [libraryResult, activityResult] = await Promise.all([
			ZUI.getLibrary(),
			ZUI.getReadingActivityStats(365)
		]);

		if (!libraryResult.ok) {
			error = libraryResult.error;
			isLoading = false;
			return;
		}

		if (!activityResult.ok) {
			error = activityResult.error;
			isLoading = false;
			return;
		}

		books = libraryResult.value.books;
		activity = activityResult.value;
		isLoading = false;
	}

	function getBookStatus(book: LibraryBook): BookStatus {
		if (book.read_at) return 'Completed';
		if ((book.progressPercent ?? 0) > 0) return 'Reading';
		return 'Unread';
	}

	function getFormat(book: LibraryBook): string {
		return (book.extension ?? 'UNKNOWN').toUpperCase();
	}

	function formatDate(dateInput: string | null | undefined): string {
		if (!dateInput) return '—';
		return new Date(dateInput).toLocaleDateString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric'
		});
	}

	function formatNumber(value: number): string {
		return value.toLocaleString('en-US');
	}

	function toDailyLabel(dateKey: string): string {
		const date = new Date(`${dateKey}T00:00:00.000Z`);
		return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' });
	}

	function getHeatColor(pages: number, maxPages: number): string {
		if (pages === 0 || maxPages <= 0) return '#1e2230';
		const ratio = pages / maxPages;
		if (ratio < 0.15) return '#2a2518';
		if (ratio < 0.3) return '#3d3520';
		if (ratio < 0.5) return '#5a4a2a';
		if (ratio < 0.7) return '#8a7540';
		return '#c9a962';
	}

	function buildHeatmap(input: ReadingActivityDay[]): {
		weeks: Array<Array<{ date: string; pagesRead: number } | null>>;
		monthLabels: Array<{ label: string; col: number }>;
		maxPages: number;
	} {
		if (input.length === 0) {
			return { weeks: [], monthLabels: [], maxPages: 0 };
		}

		const dateMap = new Map(input.map((entry) => [entry.date, entry.pagesRead]));
		const start = new Date(`${input[0].date}T00:00:00.000Z`);
		const end = new Date(`${input[input.length - 1].date}T00:00:00.000Z`);
		const adjustedStart = new Date(start);
		while (adjustedStart.getUTCDay() !== 1) {
			adjustedStart.setUTCDate(adjustedStart.getUTCDate() - 1);
		}

		const weeks: Array<Array<{ date: string; pagesRead: number } | null>> = [];
		const monthLabels: Array<{ label: string; col: number }> = [];
		let maxPages = 0;
		let week: Array<{ date: string; pagesRead: number } | null> = Array(7).fill(null);
		let weekIndex = 0;
		let lastMonth = '';
		let cursor = new Date(adjustedStart);

		while (cursor <= end) {
			const dateKey = cursor.toISOString().slice(0, 10);
			const dayOfWeek = cursor.getUTCDay() === 0 ? 6 : cursor.getUTCDay() - 1;
			const pagesRead = dateMap.get(dateKey) ?? 0;
			maxPages = Math.max(maxPages, pagesRead);

			if (dateMap.has(dateKey)) {
				week[dayOfWeek] = { date: dateKey, pagesRead };
			}

			const monthKey = `${cursor.getUTCFullYear()}-${cursor.getUTCMonth()}`;
			if (monthKey !== lastMonth) {
				monthLabels.push({
					label: cursor.toLocaleDateString('en-US', { month: 'short', timeZone: 'UTC' }),
					col: weekIndex
				});
				lastMonth = monthKey;
			}

			if (dayOfWeek === 6) {
				weeks.push(week);
				week = Array(7).fill(null);
				weekIndex += 1;
			}

			cursor.setUTCDate(cursor.getUTCDate() + 1);
		}

		if (week.some((cell) => cell !== null)) {
			weeks.push(week);
		}

		return { weeks, monthLabels, maxPages };
	}

	function buildConicGradient(entries: Array<{ value: number }>, colors: string[]): string {
		const total = entries.reduce((sum, entry) => sum + entry.value, 0);
		if (total <= 0) {
			return '#1e2230';
		}

		let offset = 0;
		const segments = entries.map((entry, index) => {
			const start = (offset / total) * 360;
			offset += entry.value;
			const end = (offset / total) * 360;
			return `${colors[index % colors.length]} ${start}deg ${end}deg`;
		});

		return `conic-gradient(${segments.join(', ')})`;
	}

	let completedBooksCount = $derived(books.filter((book) => Boolean(book.read_at)).length);
	let readingBooksCount = $derived(books.filter((book) => getBookStatus(book) === 'Reading').length);
	let unreadBooksCount = $derived(books.filter((book) => getBookStatus(book) === 'Unread').length);

	let booksByFormat = $derived.by(() => {
		const counts = new Map<string, number>();
		for (const book of books) {
			const format = getFormat(book);
			counts.set(format, (counts.get(format) ?? 0) + 1);
		}
		return Array.from(counts.entries())
			.map(([name, value]) => ({ name, value }))
			.sort((a, b) => b.value - a.value);
	});

	let booksByStatus = $derived([
		{ name: 'Unread' as BookStatus, value: unreadBooksCount },
		{ name: 'Reading' as BookStatus, value: readingBooksCount },
		{ name: 'Completed' as BookStatus, value: completedBooksCount }
	]);

	let ratingDistribution = $derived.by(() => {
		const counts = [0, 0, 0, 0, 0, 0];
		for (const book of books) {
			const rating = book.rating ?? 0;
			if (rating >= 1 && rating <= 5) {
				counts[rating] += 1;
			}
		}
		return [1, 2, 3, 4, 5].map((rating) => ({ label: `${rating}★`, value: counts[rating] }));
	});

	let recentDaily = $derived.by(() => {
		if (!activity) return [];
		return activity.daily.slice(-dailyRange).map((entry) => ({
			...entry,
			label: toDailyLabel(entry.date)
		}));
	});

	let recentWeekly = $derived.by(() => {
		if (!activity) return [];
		return activity.weekly.slice(-12);
	});

	let recentMonthly = $derived.by(() => {
		if (!activity) return [];
		return activity.monthly;
	});

	let heatmap = $derived.by(() => buildHeatmap(activity?.daily ?? []));

	let maxDailyPages = $derived(Math.max(...recentDaily.map((entry) => entry.pagesRead), 1));
	let maxWeeklyPages = $derived(Math.max(...recentWeekly.map((entry) => entry.pages), 1));
	let maxHourlyPages = $derived(Math.max(...(activity?.hourly ?? []).map((entry) => entry.pages), 1));
	let maxMonthlyPages = $derived(Math.max(...recentMonthly.map((entry) => entry.pages), 1));
	let maxRatingCount = $derived(Math.max(...ratingDistribution.map((entry) => entry.value), 1));
	let maxStatusCount = $derived(Math.max(...booksByStatus.map((entry) => entry.value), 1));

	let readingPercentage = $derived.by(() => {
		if (!activity || activity.totals.totalDays <= 0) return 0;
		return Math.round((activity.totals.daysActive / activity.totals.totalDays) * 100);
	});

	let formatPieGradient = $derived(buildConicGradient(booksByFormat, FORMAT_COLORS));

	let streakPreviewCells = $derived.by(() => {
		if (!activity) return [] as number[];
		const count = Math.min(activity.streak.current, 14);
		return Array.from({ length: count }, (_, index) => index);
	});
</script>

<div class="stats-page">
	<Loading bind:show={isLoading} />

	{#if error}
		<div class="error-banner">
			<p>{error.message}</p>
			<button onclick={loadStats}>Retry</button>
		</div>
	{/if}

	{#if activity}
		<section class="summary-grid" aria-label="Summary stats">
			<article class="summary-card">
				<p>Total Pages Read</p>
				<h2>{formatNumber(activity.totals.totalPages)}</h2>
				<span>{activity.totals.avgPagesPerDay} avg/day</span>
			</article>
			<article class="summary-card">
				<p>Current Streak</p>
				<h2 class="accent-red">{activity.streak.current} days</h2>
				<span>Longest: {activity.streak.longest} days</span>
			</article>
			<article class="summary-card">
				<p>Days Active</p>
				<h2 class="accent-green">{activity.totals.daysActive}</h2>
				<span>{readingPercentage}% of days</span>
			</article>
			<article class="summary-card">
				<p>Books Completed</p>
				<h2 class="accent-blue">{completedBooksCount}</h2>
				<span>{books.length} books in library</span>
			</article>
		</section>

		<section class="highlight-grid" aria-label="Highlights">
			<article class="highlight-card">
				<p>Best Reading Day</p>
				<h3>{activity.totals.bestDay.pagesRead} pages</h3>
				<span>{formatDate(activity.totals.bestDay.date)}</span>
			</article>
			<article class="highlight-card">
				<p>Avg on Active Days</p>
				<h3>{activity.totals.avgPagesOnActiveDay} pages</h3>
				<span>{formatNumber(activity.totals.totalSessions)} progress snapshots</span>
			</article>
			<article class="highlight-card">
				<p>Reading Mix</p>
				<h3>{readingBooksCount} reading / {unreadBooksCount} unread</h3>
				<span>{completedBooksCount} completed</span>
			</article>
		</section>

		<section class="card heatmap-card">
			<div class="card-head">
				<h3>Reading Activity</h3>
				<p>{formatNumber(activity.totals.totalPages)} pages in the last year</p>
			</div>

			{#if heatmap.weeks.length > 0}
				<div class="heatmap-shell">
					<div class="month-labels">
						{#each heatmap.monthLabels as label}
							<span style={`left: ${label.col * 16}px`}>{label.label}</span>
						{/each}
					</div>

					<div class="heatmap-grid-wrap">
						<div class="day-labels">
							<span>Mon</span>
							<span></span>
							<span>Wed</span>
							<span></span>
							<span>Fri</span>
							<span></span>
							<span>Sun</span>
						</div>
						<div class="heatmap-weeks">
							{#each heatmap.weeks as week}
								<div class="heatmap-week">
									{#each week as cell}
										{#if cell}
											<div
												class="heat-cell"
												style={`background: ${getHeatColor(cell.pagesRead, heatmap.maxPages)}`}
												title={`${formatDate(cell.date)}: ${cell.pagesRead} pages`}
											></div>
										{:else}
											<div class="heat-cell empty"></div>
										{/if}
									{/each}
								</div>
							{/each}
						</div>
					</div>

					<div class="heat-legend">
						<span>Less</span>
						{#each [0, 0.15, 0.3, 0.5, 0.7, 1] as ratio}
							<div style={`background: ${ratio === 0 ? '#1e2230' : getHeatColor(heatmap.maxPages * ratio, heatmap.maxPages)}`}></div>
						{/each}
						<span>More</span>
					</div>
				</div>
			{/if}
		</section>

		<section class="card">
			<div class="card-head">
				<h3>Pages Per Day</h3>
				<div class="range-switch">
					{#each DAILY_RANGES as range}
						<button type="button" class:active={dailyRange === range} onclick={() => (dailyRange = range)}>
							{range}d
						</button>
					{/each}
				</div>
			</div>

			<div class="bar-chart" data-compact={dailyRange === 30}>
				{#each recentDaily as item}
					<div class="bar-col" title={`${formatDate(item.date)}: ${item.pagesRead} pages`}>
						<div class="bar-track">
							<div class="bar-fill gold" style={`height: ${(item.pagesRead / maxDailyPages) * 100}%`}></div>
						</div>
						<span>{item.label}</span>
					</div>
				{/each}
			</div>
		</section>

		<section class="split-grid">
			<article class="card">
				<div class="card-head">
					<h3>Weekly Trend</h3>
				</div>
				<div class="bar-chart weekly-chart">
					{#each recentWeekly as item}
						<div class="bar-col" title={`${item.week}: ${item.pages} pages`}>
							<div class="bar-track">
								<div class="bar-fill gold-soft" style={`height: ${(item.pages / maxWeeklyPages) * 100}%`}></div>
							</div>
							<span>{item.week}</span>
						</div>
					{/each}
				</div>
			</article>

			<article class="card">
				<div class="card-head">
					<h3>Reading by Time of Day</h3>
				</div>
				<div class="bar-chart hourly-chart">
					{#each activity.hourly as item}
						<div class="bar-col" title={`${item.label}: ${item.pages} pages`}>
							<div class="bar-track">
								<div class="bar-fill blue" style={`height: ${(item.pages / maxHourlyPages) * 100}%`}></div>
							</div>
							<span>{item.label}</span>
						</div>
					{/each}
				</div>
			</article>
		</section>

		<section class="split-grid monthly-grid">
			<article class="card monthly-card">
				<div class="card-head">
					<h3>Monthly Overview</h3>
				</div>
				<div class="monthly-bars">
					{#each recentMonthly as month}
						<div class="monthly-row" title={`${month.month}: ${month.pages} pages, ${month.booksFinished} books finished`}>
							<div class="month-label">{month.month}</div>
							<div class="month-track">
								<div class="month-fill" style={`width: ${(month.pages / maxMonthlyPages) * 100}%`}></div>
							</div>
							<div class="month-values">
								<span>{formatNumber(month.pages)}</span>
								<em>{month.booksFinished}</em>
							</div>
						</div>
					{/each}
				</div>

				<div class="monthly-table-wrap">
					<table>
						<thead>
							<tr>
								<th>Month</th>
								<th>Pages</th>
								<th>Avg/Day</th>
								<th>Books Done</th>
							</tr>
						</thead>
						<tbody>
							{#each [...recentMonthly].slice(-6).reverse() as month}
								<tr>
									<td>{month.month}</td>
									<td>{formatNumber(month.pages)}</td>
									<td>{month.avgPagesPerDay}</td>
									<td>{month.booksFinished > 0 ? month.booksFinished : '—'}</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</article>

			<div class="distribution-stack">
				<article class="card">
					<div class="card-head"><h3>Books by Format</h3></div>
					<div class="pie-wrap">
						<div class="pie" style={`background: ${formatPieGradient}`}></div>
						<div class="pie-hole"></div>
					</div>
					<div class="legend-grid">
						{#each booksByFormat as format, index}
							<div>
								<span style={`background: ${FORMAT_COLORS[index % FORMAT_COLORS.length]}`}></span>
								<p>{format.name} ({format.value})</p>
							</div>
						{/each}
					</div>
				</article>

				<article class="card">
					<div class="card-head"><h3>Rating Distribution</h3></div>
					<div class="rating-bars">
						{#each ratingDistribution as rating}
							<div class="rating-row" title={`${rating.label}: ${rating.value} books`}>
								<span>{rating.label}</span>
								<div class="rating-track">
									<div class="rating-fill" style={`width: ${(rating.value / maxRatingCount) * 100}%`}></div>
								</div>
								<em>{rating.value}</em>
							</div>
						{/each}
					</div>
				</article>

				<article class="card">
					<div class="card-head"><h3>Books by Status</h3></div>
					<div class="status-bars">
						{#each booksByStatus as status}
							{@const pct = books.length > 0 ? Math.round((status.value / books.length) * 100) : 0}
							<div class="status-row">
								<div class="status-head">
									<span>{status.name}</span>
									<em>{status.value} ({pct}%)</em>
								</div>
								<div class="status-track">
									<div class="status-fill" style={`width: ${(status.value / maxStatusCount) * 100}%; background: ${STATUS_COLORS[status.name]}`}></div>
								</div>
							</div>
						{/each}
					</div>
				</article>
			</div>
		</section>

		<section class="card streak-card">
			<div class="card-head"><h3>Reading Streaks</h3></div>
			<div class="streak-grid">
				<div class="streak-box">
					<p>Current Streak</p>
					<div class="streak-main"><strong>{activity.streak.current}</strong><span>days</span></div>
					<div class="streak-cells">
						{#each streakPreviewCells as cell}
							<div style={`opacity: ${0.3 + (cell / Math.max(streakPreviewCells.length, 1)) * 0.7}`}></div>
						{/each}
						{#if activity.streak.current > 14}
							<em>+{activity.streak.current - 14}</em>
						{/if}
					</div>
				</div>
				<div class="streak-box">
					<p>Longest Streak</p>
					<div class="streak-main"><strong>{activity.streak.longest}</strong><span>days</span></div>
					<div class="streak-range">
						{#if activity.streak.longestStart && activity.streak.longestEnd}
							{formatDate(activity.streak.longestStart)} — {formatDate(activity.streak.longestEnd)}
						{:else}
							—
						{/if}
					</div>
				</div>
			</div>
		</section>
	{/if}
</div>

<style>
	.stats-page {
		padding: 1.5rem 0;
		display: grid;
		gap: 1.5rem;
		color: var(--color-text-primary);
	}

	.error-banner {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.75rem;
		padding: 0.625rem 0.75rem;
		border-radius: 0.5rem;
		border: 1px solid color-mix(in oklab, var(--color-danger), transparent 80%);
		background: color-mix(in oklab, var(--color-danger), transparent 95%);
		color: var(--color-danger);
	}

	.error-banner p {
		margin: 0;
		font-size: 0.8rem;
	}

	.error-banner button {
		padding: 0.35rem 0.7rem;
		border-radius: 0.5rem;
		border: 1px solid color-mix(in oklab, var(--color-danger), transparent 65%);
		background: transparent;
		color: var(--color-danger);
		font-size: 0.75rem;
		font-family: inherit;
		cursor: pointer;
	}

	.summary-grid,
	.highlight-grid,
	.split-grid,
	.streak-grid {
		display: grid;
		gap: 0.75rem;
	}

	.summary-grid {
		grid-template-columns: repeat(4, minmax(0, 1fr));
	}

	.summary-card,
	.highlight-card,
	.card {
		background: #161921;
		border: 1px solid var(--color-border);
		border-radius: 0.75rem;
		padding: 1rem;
	}

	.summary-card p,
	.highlight-card p {
		margin: 0;
		font-size: 0.75rem;
		color: var(--color-text-muted);
	}

	.summary-card h2 {
		margin: 0.25rem 0 0;
		font-size: 1.55rem;
		font-weight: 500;
		line-height: 1.15;
	}

	.summary-card h2.accent-red {
		color: #f87171;
	}

	.summary-card h2.accent-green {
		color: #4ade80;
	}

	.summary-card h2.accent-blue {
		color: #60a5fa;
	}

	.summary-card span,
	.highlight-card span {
		display: block;
		margin-top: 0.25rem;
		font-size: 0.72rem;
		color: var(--color-text-muted);
	}

	.highlight-grid {
		grid-template-columns: repeat(3, minmax(0, 1fr));
	}

	.highlight-card h3 {
		margin: 0.3rem 0 0;
		font-size: 1rem;
		font-weight: 500;
		line-height: 1.2;
	}

	.card-head {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.75rem;
		margin-bottom: 0.75rem;
	}

	.card-head h3 {
		margin: 0;
		font-size: 1rem;
		font-weight: 600;
	}

	.card-head p {
		margin: 0;
		font-size: 0.75rem;
		color: var(--color-text-muted);
	}

	.range-switch {
		display: inline-flex;
		align-items: center;
		background: #1e2230;
		border: 1px solid var(--color-border);
		border-radius: 0.5rem;
		padding: 0.125rem;
		gap: 0.125rem;
	}

	.range-switch button {
		padding: 0.28rem 0.52rem;
		border-radius: 0.36rem;
		border: 0;
		background: transparent;
		color: var(--color-text-muted);
		font-size: 0.7rem;
		font-family: inherit;
		cursor: pointer;
	}

	.range-switch button.active {
		background: #161921;
		color: var(--color-text-primary);
	}

	.heatmap-shell {
		position: relative;
	}

	.month-labels {
		position: relative;
		height: 1rem;
		margin-left: 1.75rem;
	}

	.month-labels span {
		position: absolute;
		top: 0;
		font-size: 0.62rem;
		color: var(--color-text-muted);
	}

	.heatmap-grid-wrap {
		display: flex;
		align-items: flex-start;
		gap: 0.45rem;
		margin-top: 0.25rem;
		overflow-x: auto;
	}

	.day-labels {
		display: grid;
		grid-template-rows: repeat(7, 13px);
		row-gap: 3px;
		width: 1.4rem;
	}

	.day-labels span {
		font-size: 0.62rem;
		color: var(--color-text-muted);
		line-height: 13px;
	}

	.heatmap-weeks {
		display: flex;
		gap: 3px;
	}

	.heatmap-week {
		display: grid;
		grid-template-rows: repeat(7, 13px);
		row-gap: 3px;
	}

	.heat-cell {
		width: 13px;
		height: 13px;
		border-radius: 3px;
	}

	.heat-cell.empty {
		background: transparent;
	}

	.heat-legend {
		display: flex;
		align-items: center;
		justify-content: flex-end;
		gap: 0.28rem;
		margin-top: 0.75rem;
	}

	.heat-legend span {
		font-size: 0.62rem;
		color: var(--color-text-muted);
	}

	.heat-legend div {
		width: 11px;
		height: 11px;
		border-radius: 2px;
	}

	.bar-chart {
		display: flex;
		align-items: flex-end;
		gap: 0.34rem;
		min-height: 12rem;
		overflow-x: auto;
		padding-bottom: 0.15rem;
	}

	.bar-col {
		display: grid;
		justify-items: center;
		gap: 0.3rem;
		min-width: 1.1rem;
	}

	.bar-track {
		width: 100%;
		height: 10.2rem;
		background: #1e2230;
		border-radius: 0.35rem;
		overflow: hidden;
		display: flex;
		align-items: flex-end;
	}

	.bar-fill {
		width: 100%;
		border-radius: 0.35rem;
	}

	.bar-fill.gold {
		background: #c9a962;
	}

	.bar-fill.gold-soft {
		background: color-mix(in oklab, #c9a962, #ffffff 8%);
	}

	.bar-fill.blue {
		background: #60a5fa;
	}

	.bar-col span {
		font-size: 0.62rem;
		color: var(--color-text-muted);
		text-align: center;
		line-height: 1.1;
		max-width: 2.4rem;
	}

	.bar-chart[data-compact='true'] .bar-col span {
		max-width: 2.2rem;
	}

	.weekly-chart .bar-track,
	.hourly-chart .bar-track {
		height: 9rem;
	}

	.split-grid {
		grid-template-columns: repeat(2, minmax(0, 1fr));
	}

	.monthly-grid {
		align-items: start;
	}

	.monthly-card {
		display: grid;
		gap: 1rem;
	}

	.monthly-bars {
		display: grid;
		gap: 0.45rem;
	}

	.monthly-row {
		display: grid;
		grid-template-columns: 6.6rem 1fr auto;
		align-items: center;
		gap: 0.6rem;
	}

	.month-label {
		font-size: 0.72rem;
		color: var(--color-text-secondary);
	}

	.month-track {
		height: 0.45rem;
		border-radius: 999px;
		overflow: hidden;
		background: #1e2230;
	}

	.month-fill {
		height: 100%;
		border-radius: 999px;
		background: linear-gradient(90deg, #c9a962, #e0c878);
	}

	.month-values {
		display: inline-flex;
		align-items: center;
		gap: 0.55rem;
		font-size: 0.7rem;
	}

	.month-values span {
		color: var(--color-text-secondary);
	}

	.month-values em {
		font-style: normal;
		color: #4ade80;
	}

	.monthly-table-wrap {
		overflow-x: auto;
	}

	table {
		width: 100%;
		border-collapse: collapse;
		font-size: 0.74rem;
	}

	thead th {
		text-align: right;
		padding: 0.42rem 0.5rem;
		color: var(--color-text-muted);
		font-weight: 500;
		border-bottom: 1px solid var(--color-border);
	}

	thead th:first-child,
	tbody td:first-child {
		text-align: left;
		padding-left: 0;
	}

	tbody td {
		padding: 0.42rem 0.5rem;
		text-align: right;
		border-bottom: 1px solid color-mix(in oklab, var(--color-border), transparent 45%);
		color: var(--color-text-secondary);
	}

	tbody tr:last-child td {
		border-bottom: 0;
	}

	.distribution-stack {
		display: grid;
		gap: 0.75rem;
	}

	.pie-wrap {
		position: relative;
		width: 8.4rem;
		height: 8.4rem;
		margin: 0 auto;
	}

	.pie,
	.pie-hole {
		position: absolute;
		inset: 0;
		border-radius: 50%;
	}

	.pie-hole {
		inset: 28%;
		background: #161921;
		border: 1px solid var(--color-border);
	}

	.legend-grid {
		display: grid;
		gap: 0.4rem;
		margin-top: 0.8rem;
	}

	.legend-grid div {
		display: inline-flex;
		align-items: center;
		gap: 0.38rem;
	}

	.legend-grid span {
		display: inline-block;
		width: 0.55rem;
		height: 0.55rem;
		border-radius: 2px;
	}

	.legend-grid p {
		margin: 0;
		font-size: 0.72rem;
		color: var(--color-text-muted);
	}

	.rating-bars,
	.status-bars {
		display: grid;
		gap: 0.5rem;
	}

	.rating-row {
		display: grid;
		grid-template-columns: 2.2rem 1fr auto;
		align-items: center;
		gap: 0.5rem;
	}

	.rating-row span,
	.rating-row em {
		font-size: 0.72rem;
		font-style: normal;
	}

	.rating-row span {
		color: var(--color-text-secondary);
	}

	.rating-row em {
		color: var(--color-text-muted);
	}

	.rating-track,
	.status-track {
		height: 0.38rem;
		border-radius: 999px;
		overflow: hidden;
		background: #1e2230;
	}

	.rating-fill {
		height: 100%;
		border-radius: 999px;
		background: #c9a962;
	}

	.status-row {
		display: grid;
		gap: 0.22rem;
	}

	.status-head {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.5rem;
	}

	.status-head span,
	.status-head em {
		font-size: 0.72rem;
	}

	.status-head span {
		color: var(--color-text-secondary);
	}

	.status-head em {
		font-style: normal;
		color: var(--color-text-muted);
	}

	.status-fill {
		height: 100%;
		border-radius: 999px;
	}

	.streak-grid {
		grid-template-columns: repeat(2, minmax(0, 1fr));
	}

	.streak-box {
		background: color-mix(in oklab, var(--color-secondary), transparent 70%);
		border: 1px solid color-mix(in oklab, var(--color-border), transparent 20%);
		border-radius: 0.75rem;
		padding: 1rem;
	}

	.streak-box > p {
		margin: 0;
		font-size: 0.75rem;
		color: var(--color-text-muted);
	}

	.streak-main {
		display: inline-flex;
		align-items: baseline;
		gap: 0.35rem;
		margin-top: 0.45rem;
	}

	.streak-main strong {
		font-size: 2rem;
		line-height: 1;
		font-weight: 500;
	}

	.streak-main span {
		font-size: 0.8rem;
		color: var(--color-text-muted);
	}

	.streak-cells {
		display: flex;
		align-items: center;
		gap: 0.2rem;
		margin-top: 0.6rem;
	}

	.streak-cells div {
		width: 0.68rem;
		height: 0.68rem;
		border-radius: 2px;
		background: #f87171;
	}

	.streak-cells em,
	.streak-range {
		font-style: normal;
		font-size: 0.72rem;
		color: var(--color-text-muted);
	}

	.streak-range {
		margin-top: 0.6rem;
	}

	@media (max-width: 1240px) {
		.summary-grid {
			grid-template-columns: repeat(2, minmax(0, 1fr));
		}

		.split-grid,
		.streak-grid,
		.highlight-grid {
			grid-template-columns: minmax(0, 1fr);
		}
	}

	@media (max-width: 760px) {
		.stats-page {
			padding-top: 1rem;
			gap: 1rem;
		}

		.summary-grid {
			grid-template-columns: minmax(0, 1fr);
		}

		.monthly-row {
			grid-template-columns: 1fr;
			gap: 0.32rem;
		}

		.month-values {
			justify-content: space-between;
		}

		.bar-col {
			min-width: 0.95rem;
		}
	}
</style>
